Rename test to: regression-60 ->  regression60
file:///home/bollu/work/asterius/asterius/test/regression-60/regression-60.mjs:2
import regression-60 from "./regression-60.lib.mjs";
                 ^

SyntaxError: Unexpected token -
    at Loader.moduleStrategy (internal/modules/esm/translators.js:48:18)
    at async link (internal/modules/esm/module_job.js:38:36)
ahc-link: callProcess: node "--experimental-modules" "regression-60.mjs" (exit 1): failed